name: Titanic Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  start-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Start Pipeline
        run: echo "Starting pipeline"

  train-model:
    needs: start-pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model-config:
          - { n_trees: 10, max_features: "log2" }
          - { n_trees: 20, max_features: "sqrt" }
          - { n_trees: 20, max_features: "log2" }
          - { n_trees: 50, max_features: "sqrt" }
    container:
      image: linogaliana/application:v0.0.4
    env:
      MLFLOW_TRACKING_URI: "${{ secrets.MLFLOW_TRACKING_URI }}"
      MLFLOW_TRACKING_USERNAME: "${{ secrets.MLFLOW_TRACKING_USERNAME }}"
      MLFLOW_TRACKING_PASSWORD: "${{ secrets.MLFLOW_TRACKING_PASSWORD }}"
      MLFLOW_EXPERIMENT_NAME: "titanicml"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_S3_ENDPOINT: "minio.lab.sspcloud.fr"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_SESSION_TOKEN: "${{ secrets.AWS_SESSION_TOKEN }}"
      JETON_API: "${{ secrets.JETON_API }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'linogaliana/application'

      - name: Train Model
        run: |
          uv run train.py --n_trees=${{ matrix.model-config.n_trees }} --max_features=${{ matrix.model-config.max_features }}